DROP DATABASE IF EXISTS VK;
CREATE DATABASE VK;
USE VK;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50) COMMENT 'ФаУШль', -- COMMENT на слсчай, �?слШ ШУя н�?нч�?вШХнн�?
    EMAIL VARCHAR(120) UNIQUE,
 	PASSWORD_HASH VARCHAR(100), -- 123456 => VZX;CLVGKAJRPO9UDFXVSLDKRN24L5456345T
	PHONE BIGINT UNSIGNED UNIQUE, 
	
    INDEX USERS_FIRSTNAME_LASTNAME_IDX(FIRSTNAME, LASTNAME)
) COMMENT 'юз�?ры';

DROP TABLE IF EXISTS `PROFILES`;
CREATE TABLE `PROFILES` (
	USER_ID BIGINT UNSIGNED NOT NULL UNIQUE,
    GENDER CHAR(1),
    BIRTHDAY DATE,
	PHOTO_ID BIGINT UNSIGNED NULL,
    CREATED_AT DATETIME DEFAULT NOW(),
    HOMETOWN VARCHAR(100)
	
    -- , FOREIGN KEY (PHOTO_ID) REFERENCES MEDIA(ID) -- ЯнЪа ранн, т.Ъ. таблШцы MEDIA �?щ�? н�?т
);

ALTER TABLE `PROFILES` ADD CONSTRAINT FK_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    ON UPDATE CASCADE -- (знач�?нШ�? Ян сУнлчанШю)
    ON DELETE RESTRICT; -- (знач�?нШ�? Ян сУнлчанШю)

DROP TABLE IF EXISTS MESSAGES;
CREATE TABLE MESSAGES (
	ID SERIAL, -- SERIAL = BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE
	FROM_USER_ID BIGINT UNSIGNED NOT NULL,
    TO_USER_ID BIGINT UNSIGNED NOT NULL,
    BODY TEXT,
    CREATED_AT DATETIME DEFAULT NOW(), -- Унжнн бсХ�?т Хаж�? н�? сЯнУШнать этн Янл�? ЯрШ вставЪ�?

    FOREIGN KEY (FROM_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (TO_USER_ID) REFERENCES USERS(ID)
);

DROP TABLE IF EXISTS FRIEND_REQUESTS;
CREATE TABLE FRIEND_REQUESTS (
	-- ID SERIAL, -- ШзУ�?нШлШ на снставннй Ълюч (INITIATOR_USER_ID, TARGET_USER_ID)
	INITIATOR_USER_ID BIGINT UNSIGNED NOT NULL,
    TARGET_USER_ID BIGINT UNSIGNED NOT NULL,
    `STATUS` ENUM('REQUESTED', 'APPROVED', 'DECLINED', 'UNFRIENDED'),
    -- `STATUS` TINYINT(1) UNSIGNED, -- в этнУ слсча�? в ЪнХ�? хранШлШ бы цШфШрный ENUM (0, 1, 2, 3...)
	REQUESTED_AT DATETIME DEFAULT NOW(),
	UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP, -- Унжнн бсХ�?т Хаж�? н�? сЯнУШнать этн Янл�? ЯрШ нбннвл�?нШШ
	
    PRIMARY KEY (INITIATOR_USER_ID, TARGET_USER_ID),
    FOREIGN KEY (INITIATOR_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (TARGET_USER_ID) REFERENCES USERS(ID)-- ,
    -- CHECK (INITIATOR_USER_ID <> TARGET_USER_ID)
);
-- чтнбы Янльзнват�?ль саУ с�?б�? н�? нтЯравШл заЯрнс в Хрсзья
ALTER TABLE FRIEND_REQUESTS 
ADD CHECK(INITIATOR_USER_ID <> TARGET_USER_ID);

DROP TABLE IF EXISTS COMMUNITIES;
CREATE TABLE COMMUNITIES(
	ID SERIAL,
	NAME VARCHAR(150),
	ADMIN_USER_ID BIGINT UNSIGNED NOT NULL,
	
	INDEX COMMUNITIES_NAME_IDX(NAME), -- ШнХ�?Ъсс Унжнн Хавать свн�? ШУя (COMMUNITIES_NAME_IDX)
	FOREIGN KEY (ADMIN_USER_ID) REFERENCES USERS(ID)
);

DROP TABLE IF EXISTS USERS_COMMUNITIES;
CREATE TABLE USERS_COMMUNITIES(
	USER_ID BIGINT UNSIGNED NOT NULL,
	COMMUNITY_ID BIGINT UNSIGNED NOT NULL,
  
	PRIMARY KEY (USER_ID, COMMUNITY_ID), -- чтнбы н�? былн 2 заЯШс�?й н Янльзнват�?л�? Ш сннбщ�?ств�?
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (COMMUNITY_ID) REFERENCES COMMUNITIES(ID)
);

DROP TABLE IF EXISTS MEDIA_TYPES;
CREATE TABLE MEDIA_TYPES(
	ID SERIAL,
    NAME VARCHAR(255), -- заЯШс�?й Уалн, ЯнэтнУс в ШнХ�?Ъс�? н�?т н�?нбхнХШУнстШ
    CREATED_AT DATETIME DEFAULT NOW(),
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS MEDIA;
CREATE TABLE MEDIA(
	ID SERIAL,
    MEDIA_TYPE_ID BIGINT UNSIGNED NOT NULL,
    USER_ID BIGINT UNSIGNED NOT NULL,
  	BODY TEXT,
    FILENAME VARCHAR(255),
    -- FILE BLOB,    	
    SIZE INT,
	METADATA JSON,
    CREATED_AT DATETIME DEFAULT NOW(),
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (MEDIA_TYPE_ID) REFERENCES MEDIA_TYPES(ID)
);

DROP TABLE IF EXISTS LIKES;
CREATE TABLE LIKES(
	ID SERIAL,
    USER_ID BIGINT UNSIGNED NOT NULL,
    MEDIA_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT DATETIME DEFAULT NOW()

    -- PRIMARY KEY (USER_ID, MEDIA_ID) � Унжнн былн Ш таЪ вУ�?стн ID в Ъач�?ств�? PK
  	-- слШшЪнУ свл�?Ъаться ШнХ�?ЪсаУШ тнж�? нЯаснн, рацШннальн�?�? Шх Хнбавлять Ян У�?р�? н�?нбхнХШУнстШ (наЯр., ЯрнвШсают Ян вр�?У�?нШ ЪаЪШ�?-тн заЯрнсы)  

/* наУ�?р�?ннн забылШ, чтнбы ЯнзХн�?�? свШХ�?ть Шх нтсстствШ�? в ER-ХШавраУУ�?
    , FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    , FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA(ID)
*/
);

DROP TABLE IF EXISTS `PHOTO_ALBUMS`;
CREATE TABLE `PHOTO_ALBUMS` (
	`ID` SERIAL,
	`NAME` VARCHAR(255) DEFAULT NULL,
    `USER_ID` BIGINT UNSIGNED DEFAULT NULL,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  	PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `PHOTOS`;
CREATE TABLE `PHOTOS` (
	ID SERIAL,
	`ALBUM_ID` BIGINT UNSIGNED NULL,
	`MEDIA_ID` BIGINT UNSIGNED NOT NULL,

	FOREIGN KEY (ALBUM_ID) REFERENCES PHOTO_ALBUMS(ID),
    FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA(ID)
);

ALTER TABLE VK.LIKES 
ADD CONSTRAINT LIKES_FK 
FOREIGN KEY (MEDIA_ID) REFERENCES VK.MEDIA(ID);

ALTER TABLE VK.LIKES 
ADD CONSTRAINT LIKES_FK_1 
FOREIGN KEY (USER_ID) REFERENCES VK.USERS(ID);

ALTER TABLE VK.PROFILES 
ADD CONSTRAINT PROFILES_FK_1 
FOREIGN KEY (PHOTO_ID) REFERENCES MEDIA(ID);
